Wchl.WMBlog.WebUI/Areas/admin/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wchl.WMBlog.IServices;
using Wchl.WMBlog.Model.Models;
using Wchl.WMBlog.WebCore;

namespace Wchl.WMBlog.WebUI.Areas.admin.Controllers
{
    public class UserInfoController : BaseController
    {
        IsysUserInfoServices UserInfoService;

        public UserInfoController(IsysUserInfoServices UserInfoService)
        {
            this.UserInfoService = UserInfoService;
        }
        // GET: admin/UserInfo
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(sysUserInfo model)
        {
            UserInfoService.Add(model);
            UserInfoService.SaverChanges();
            return WriteSuccess("添加成功");
        }
        public ActionResult GetData()
        {
            int pageIndex = Request["start"] != null ? int.Parse(Request["start"]) : 1;
            int pageSize = Request["length"] != null ? int.Parse(Request["length"]) : 5;
            int draw = Request["draw"] != null ? int.Parse(Request["draw"]) : 1;
            int totalCount;
            short delFlag = 0;
            var userInfoList = UserInfoService.QueryByBeginPage<int>(pageIndex, pageSize, out totalCount, r => r.uStatus == delFlag, r => r.uID, true);
            var temp = from u in userInfoList
                       select new { ID = u.uID, UserName = u.uLoginName,UserPwd = u.uLoginPWD, RealName=u.uRealName, subtime = u.uCreateTime, Remark = u.uRemark };
            var jsonDataTemp = new
            {
                data = temp.ToList(),
                draw = draw,
                recordsTotal = totalCount,
                recordsFiltered = totalCount

            };
            return Json(jsonDataTemp, JsonRequestBehavior.AllowGet);
        }
    }
}

Wchl.WMBlog.WebUI/Areas/admin/Views/UserInfo/Add.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>添加用户信息</title>
    <link href="~/Content/CSS/zui.css" rel="stylesheet" />
    <link href="~/Content/CSS/zui-theme-blue.css" rel="stylesheet" />
    <link href="~/Content/CSS/index.css" rel="stylesheet" />
    <script src="~/Content/JS/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Content/JS/zui.js"></script>
    <script src="~/Content/lib/layer/layer.js"></script>
    <script type="text/javascript">
        $(function () {
            //关闭弹出窗口
            $("#btncancel").click(function () {
                helper.layer_close();
            })
        })

        function ajaxsuccess(ajaxobj) {
            if (ajaxobj.status == "0") {
                helper.layer_success("添加成功");
            } else {

            }
        }
    </script>
</head>
<body>
    <div class="example">
        @using (Ajax.BeginForm("add", "UserInfo", new AjaxOptions()
        {
            Url=Url.Action("add", "UserInfo"),
            HttpMethod="post",
            OnSuccess= "ajaxsuccess",
        }, new { @class = "form-horizontal" }))
        {
                <div class="row">
                    <div class="form-group">
                        <label for="intputusername" class="col-sm-2 required">用户名：</label>
                        <div class="col-md-5 col-sm-10">
                            <input type="text" class="form-control" id="intputusername" placeholder="电子邮件/手机号/用户名">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputname" class="col-sm-2 required">姓名：</label>
                        <div class="col-md-5 col-sm-10">
                            <input type="text" class="form-control" id="inputname" placeholder="姓名">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="InputPassword" class="col-sm-2 required">新密码：</label>
                        <div class="col-md-5 col-sm-10">
                            <input type="password" class="form-control" id="InputPassword" placeholder="新密码">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="verifyPassword" class="col-sm-2 required">确认密码：</label>
                        <div class="col-md-5 col-sm-10">
                            <input type="password" class="form-control" id="verifyPassword" placeholder="确认密码">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="InputEmail" class="col-sm-2 required">电子邮箱：</label>
                        <div class="col-md-5 col-sm-10">
                            <input type="email" class="form-control" id="InputEmail" placeholder="电子邮箱">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-3 col-xs-3 pull-right">
                            <button type="submit" id="btnsubmit" class="btn btn-primary">提交</button>
                            <button type="button" id="btncancel" class="btn btn-primary">取消</button>
                        </div>
                    </div>
                </div>
        }
    </div>
</body>
</html>