Wchl.WMBlog.WebUI/Controllers/BlogController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Text;
using System.Web.Mvc;
using Wchl.WMBlog.Common.ToolsHelper;
using Wchl.WMBlog.IServices;
using Wchl.WMBlog.Model.Models;
using Wchl.WMBlog.Model.VeiwModels;
using Wchl.WMBlog.WebCore;
using Wchl.WMBlog.WebUI.Models;
using Webdiyer.WebControls.Mvc;
using Wchl.WMBlog.WebCore.Attrs;

namespace Wchl.WMBlog.WebUI.Controllers
{
    [SkipCheckLogin]
    public class BlogController : BaseController
    {
        IBlogArticleServices BlogArticleServive;
        IGuestbookServices GuestbookServices;

        public BlogController(IBlogArticleServices BlogArticleServive, IGuestbookServices GuestbookServices)
        {
            this.BlogArticleServive = BlogArticleServive;
            this.GuestbookServices = GuestbookServices;

        }
        // GET: Blog
        public ActionResult Index(int id = 1)
        {
            //获取控制器名称
            ViewBag.controllername = RouteData.Values["controller"].ToString().ToLower();
            int pagesize = 6;
            var blogArticleList = BlogArticleServive.QueryOrderBy(a => a.bcategory == "技术博文",a=>a.bCreateTime,false).ToPagedList(id,pagesize);
            foreach (var item in blogArticleList)
            {
                if (!string.IsNullOrEmpty(item.bcontent))
                {
                    item.bcontent = Tools.ReplaceHtmlTag(item.bcontent);
                    if (item.bcontent.Length > 200)
                    {
                        item.bcontent = item.bcontent.Substring(0, 200);
                    }
                }
            }
            //发布时间排序
            ViewBag.blogtimelist = BlogArticleServive.QueryOrderBy(c => true, c => c.bCreateTime, false);
            //评论排序
            ViewBag.blogtrafficlist = BlogArticleServive.QueryOrderBy(c => true, c => c.btraffic, false);
            //留言排序
            string sql = @"select a.*,b.btitle from (select blogId,count(1) as counts  from Guestbook group by blogId) as a
inner join BlogArticle as b
on
b.bID=a.blogId order by counts desc";

            ViewBag.blogguestbooklist = GuestbookServices.RunProc<TopgbViewModels>(sql);


            if (Request.IsAjaxRequest())
                return PartialView("_ArticleList", blogArticleList);
            return View(blogArticleList);
        }

        /// <summary>
        /// 详情页
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Detail(int id)
        {
            //获取控制器名称
            ViewBag.controllername = RouteData.Values["controller"].ToString().ToLower();
            var model = BlogArticleServive.getBlogDetails(id);
            ViewBag.gblist = GuestbookServices.QueryOrderBy(c => c.blogId == id, c => c.createdate, false).ToPagedList(1, 5);

            //发布时间排序
            ViewBag.blogtimelist = BlogArticleServive.QueryOrderBy(c => true, c => c.bCreateTime, false);
            //评论排序
            ViewBag.blogtrafficlist = BlogArticleServive.QueryOrderBy(c => true, c => c.btraffic, false);
            //留言排序
            string sql = @"select a.*,b.btitle from (select blogId,count(1) as counts  from Guestbook group by blogId) as a
inner join BlogArticle as b
on
b.bID=a.blogId order by counts desc";

            ViewBag.blogguestbooklist = GuestbookServices.RunProc<TopgbViewModels>(sql);

            return View(model);
        }

        /// <summary>
        ///提交评论
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult addGuestbook(GuestbookViewModels model)
        {
            model.createdate = DateTime.Now;
            model.ip = Request.UserHostAddress;
            //AutoMapper自动映射
            Mapper.Initialize(cfg => cfg.CreateMap<GuestbookViewModels, Guestbook > ());
            Guestbook models = Mapper.Map< GuestbookViewModels, Guestbook> (model);
            BlogArticle blogArticle = BlogArticleServive.QueryWhere(a => a.bID == model.blogId).FirstOrDefault();
            blogArticle.bcommentNum += 1;
            BlogArticleServive.SaverChanges();
            GuestbookServices.Add(models);
            GuestbookServices.SaverChanges();
            ViewBag.gblist = GuestbookServices.QueryOrderBy(c => c.blogId == model.blogId, c => c.createdate, false).ToPagedList(1, 5);
            return PartialView("_GuestbookPage");
        }

        /// <summary>
        /// js分页实现
        /// </summary>
        /// <param name="page"></param>
        /// <param name="blogId"></param>
        /// <returns></returns>
        public ActionResult getGuestbook(int page,int blogId)
        {
            StringBuilder sb = new StringBuilder();
            int pages = 0;
            var modelsLists = GuestbookServices.QueryByPage(page, 5,out pages, c => c.blogId == blogId, c => c.createdate, false);
            foreach (var item in modelsLists)
            {
                sb.AppendFormat(@"<div class='comment'>
<a href = '###' class='avatar'>
<i class='icon-user icon-2x'></i>
</a>
<div class='content'>
<div class='pull-right text-muted'>{0}</div>
<div><a href = '###' ><strong > {1}</strong ></a ></div>
<div class='text'>{2}</div>
<div class='actions'>
<a href = '##' > 回复 </a>
</div >
</div >
</div >",item.createdate,item.username,item.body);
            }
            if (pages % 5 == 0)
            {
                pages = pages / 5;
            }
            else
            {
                pages = (pages / 5)+1;
            }


            return Json(new {
                content = sb.ToString(),
                pages= pages
            });
        }
    }
}

Wchl.WMBlog.WebUI/Views/Shared/_ArticleList.cshtml
@model PagedList<BlogArticle>

@{
    foreach (var item in Model)
    {
        if (item == Model[0])
        {
            <div class="item">
                <div class="item-heading">
                    <div class="pull-right"><a href="###"><i class="icon-pencil"></i> 编辑</a> &nbsp;<a href="#"><i class="icon-remove"></i> 删除</a></div>
                    <h4><span class="label label-success">新</span>&nbsp; <a href="/blog/Detail/@item.bID" id="blogXQ">@item.btitle</a></h4>
                </div>
                <div class="item-content">
                    @item.bcontent
                </div>
                <div class="item-footer">
                    <a href="#" class="text-muted"><i class="icon-comments"></i> @item.btraffic</a>&nbsp;
                    <span class="text-muted">@item.bCreateTime</span>
                </div>
            </div>
        }
        else
        {
            <div class="item">
                <div class="item-heading">
                    <div class="pull-right"><a href="###"><i class="icon-pencil"></i> 编辑</a> &nbsp;<a href="#"><i class="icon-remove"></i> 删除</a></div>
                    <h4><a href="/blog/Detail/@item.bID">@item.btitle</a></h4>
                </div>
                <div class="item-content">
                    @item.bcontent
                </div>
                <div class="item-footer">
                    <a href="#"><i class="icon-comments"></i> @item.btraffic</a>&nbsp;
                    <span class="text-muted">@item.bCreateTime</span>
                </div>
            </div>
        }
    }
}
<div class="text-center">
    @Ajax.Pager(Model, new PagerOptions { PageIndexParameterName = "id", ContainerTagName = "ul", CssClass = "pager", CurrentPagerItemTemplate = "<li class=\"active\"><a href=\"#\">{0}</a></li>", DisabledPagerItemTemplate = "<li class=\"disabled\"><a>{0}</a></li>", PagerItemTemplate = "<li>{0}</li>" }, new MvcAjaxOptions { UpdateTargetId = "items", OnSuccess = "handleSuccess" })
</div>

Wchl.WMBlog.WebUI/Views/Shared/_CommentsList.cshtml
<div class="text-center">
    @*@Ajax.Pager(Model, new PagerOptions { PageIndexParameterName = "id", ContainerTagName = "ul", CssClass = "pager", CurrentPagerItemTemplate = "<li class=\"active\"><a href=\"#\">{0}</a></li>", DisabledPagerItemTemplate = "<li class=\"disabled\"><a>{0}</a></li>", PagerItemTemplate = "<li>{0}</li>" }, new MvcAjaxOptions { UpdateTargetId = "comments-list" })*@
</div>

Wchl.WMBlog.WebUI/Views/Shared/_FooterPage.cshtml
    <!--页脚部分-->
<div id="footer_wrapper" class="col-md-12">
    <footer>
        <ul>
            <li><a href="content.html">版权信息</a></li>
            <li><a href="content.html">站点地图</a></li>
            <li><a href="content.html">联系我们</a></li>
        </ul>
        <p>Copyright ©2016 WMBlog</p>
    </footer>
</div>
<!--页脚部分结束-->

Wchl.WMBlog.WebUI/Views/Shared/_GuestbookPage.cshtml
<article>
    <div spellcheck="false" class="example">
        <div class="comments">
            <header>
                <div class="pull-right"><a href="#commentReplyForm2" class="btn btn-primary"><i class="icon-comment-alt"></i> 发表评论</a></div>
                <h3>所有评论</h3>
            </header>
            <section class="comments-list" id="comments-list">
              @{ if (ViewBag.gblist != null)
                  {
                      foreach (var list in ViewBag.gblist)
                      {
                        <div class="comment">
                            <a href="###" class="avatar">
                                <i class="icon-user icon-2x"></i>
                            </a>
                            <div class="content">
                                <div class="pull-right text-muted">@list.createdate</div>
                                <div><a href="###"><strong>@list.username</strong></a></div>
                                <div class="text">@list.body</div>
                                <div class="actions">
                                    <a href="##">回复</a>
                                </div>
                            </div>
                        </div>
                      }
                  }

            }
            </section>
            <br />
            <div class="text-center" id="textcenter">
               
            </div>
            <footer>
                <div class="reply-form" id="commentReplyForm2">
                    <a href="###" class="avatar"><i class="icon-user icon-2x"></i></a>
                    @using (Ajax.BeginForm("addGuestbook", "Blog", new AjaxOptions()
                    {
                        HttpMethod = "post",
                        OnSuccess="su"

                    }, new { @class = "form-horizontal" }))
                    {
                        <input type="hidden" id="blogId" name="blogId" value=""/>
                        <div class="form-group col-md-4 form-inline">
                            <label for="username" class="col-xs-3">昵称</label>
                            <div>
                                <input type="text" class="form-control" name="username" id="username" placeholder="昵称">
                            </div>
                        </div>
                        <div class="form-group col-md-4 form-inline">
                            <label for="phone" class="col-xs-3">手机</label>
                            <div>
                                <input type="text" class="form-control" name="phone" id="phone" placeholder="手机">
                            </div>
                        </div>
                        <div class="form-group col-md-4 form-inline">
                            <label for="QQ" class="col-xs-3">Q Q</label>
                            <div>
                                <input type="text" class="form-control" name="QQ" id="QQ" placeholder="Q Q">
                            </div>
                        </div>
                        <div class="form-group"></div>
                        <div class="form-group">
                            <textarea class="form-control new-comment-text" id="body" name="body" rows="4" placeholder="撰写留言..."></textarea>
                        </div>
                        <div class="form-group comment-user">
                            <div class="row">
                                <div class="col-md-2 col-md-offset-10"><button type="submit" class="btn btn-block btn-primary " value="提交">提交</button></div>
                            </div>
                        </div>
                    }
                </div>
            </footer>
        </div>
    </div>
</article>

Wchl.WMBlog.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/CSS/zui.css" rel="stylesheet" />
    @*<link href="~/Content/CSS/zui-blog-theme.css" rel="stylesheet" />*@
    <link href="~/Content/CSS/zui-theme-blue.css" rel="stylesheet" />
    <link href="~/Content/CSS/HomeIndex.css" rel="stylesheet" />
    <link href="~/Content/CSS/pagerstyles.css" rel="stylesheet" />
    <title>@ViewBag.Title - WMBlog博客</title>


</head>
<body>
    <!--导航部分-->
    @Html.Partial("_NavbarPage")
    <!--主体内容-->
    <div class="main">
        <div class="row">
            <!--左边主要内容-->
            @*<article style="margin-top: 10px;">
                    <div class="col-md-8" id="leftmain">
                        @RenderBody()
                    </div>
                </article>*@
            <!--左边主要内容-->
            <!--右边栏-->
            <!--主题部分-->
            @{
                if (ViewBag.controllername != "statistical")
                {
                    <article style="margin-top: 10px;">
                        <div class="col-md-8" id="leftmain">
                            @RenderBody()
                        </div>
                    </article>
                    @Html.Partial("_RightPage")
                }
                else
                {
                    @RenderBody()
                }

            }

            <!--右边栏-->
        </div>
    </div>
    <!--主题部分-->
    <!--底部版权部分-->
    @Html.Partial("_FooterPage")

    <script src="~/Content/JS/jquery-1.12.4.min.js"></script>
    <script src="~/Content/JS/zui.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script type="text/javascript">
        $(function () {
            //用于控制导航样式
            var name = '@ViewBag.controllername'
            $('#' + name).attr("class", "active")
        })
    </script>
    @RenderSection("scripts", false)
</body>
</html>

Wchl.WMBlog.WebUI/Views/Shared/_NavbarPage.cshtml
  <!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="index.html" class="navbar-brand">WM Blog</a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li id="home"><a href="/home/index" id="index"><i class="icon icon-home"></i>&nbsp;首页</a></li>
                <li id="blog"><a href="/blog/index" id="content"><i class="icon icon-list-alt"></i>&nbsp;博文</a></li>
                <li><a href="/movie/index"><i class="icon icon-film"></i>&nbsp;随笔</a></li>
                <li><a href="/statistical/index"><i class="icon icon-bar-chart"></i>&nbsp;访问</a></li>
                <li><a href="/about/index"><span class="icon icon-tags"></span>&nbsp;关于</a></li>
            </ul>
            <form class="navbar-form navbar-right" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="搜索">
                </div>
                <button type="submit" class="btn btn-primary"><i class="icon icon-search"></i>&nbsp;搜索</button>
            </form>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->

Wchl.WMBlog.WebUI/Views/Shared/_RightPage.cshtml
<!--右边栏部分-->
<aside>
    <div class="col-md-4">
        <section class="youbianlan">
            <div class="panel-group">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="panel-title panel-info">
                            <h4>最新发布</h4>
                        </div>
                    </div>
                    <div class="panel-body">
                        <ul>
                            @{
                                if (ViewBag.blogtimelist != null)
                                {
                                    for (int i = 0; i < 10; i++)
                                    {
                                        <li><a href="/blog/Detail/@ViewBag.blogtimelist[i].bID">@ViewBag.blogtimelist[i].btitle</a></li>
                                    }
                                }

                            }
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <section class="youbianlan">
            <div class="panel-group">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="panel-title panel-info">
                            <h4>阅读排行榜</h4>
                        </div>
                    </div>
                    <div class="panel-body">
                        <ul>
                            @{
                                if (ViewBag.blogtrafficlist != null)
                                {
                                    for (int i = 0; i < 10; i++)
                                    {
                                        <li><a href="/blog/Detail/@ViewBag.blogtrafficlist[i].bID">@ViewBag.blogtrafficlist[i].btitle</a></li>
                                    }
                                }

                            }
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <section class="youbianlan">
            <div class="panel-group">
                <div class="panel">
                    <div class="panel-heading">
                        <div class="panel-title panel-info">
                            <h4>评论排行榜</h4>
                        </div>
                    </div>
                    <div class="panel-body">
                        <ul>
                            @{
                                List<TopgbViewModels> list = ViewBag.blogguestbooklist as List<TopgbViewModels>;
                                if (list != null && list.Any())
                                {
                                    if (list.Count < 10)
                                    {
                                        for (int i = 0; i < list.Count; i++)
                                        {
                                            <li><a href="/blog/Detail/@list[i].blogId">@list[i].btitle</a></li>
                                        }
                                    }
                                    else
                                    {
                                        for (int i = 0; i < 10; i++)
                                        {
                                            <li><a href="/blog/Detail/@list[i].blogId">@list[i].btitle</a></li>
                                        }
                                    }

                                }

                            }
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </div>
</aside>
<!--右边栏部分结束-->