Wchl.WMBlog.WebUI/Areas/admin/Controllers/BlogArticleController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wchl.WMBlog.Common.Cache;
using Wchl.WMBlog.IServices;
using Wchl.WMBlog.Model.Models;
using Wchl.WMBlog.WebCore;

namespace Wchl.WMBlog.WebUI.Areas.admin.Controllers
{
    public class BlogArticleController : BaseController
    {
        IBlogArticleServices BlogArticleServive;
        public BlogArticleController(IBlogArticleServices BlogArticleServive)
        {
            this.BlogArticleServive = BlogArticleServive;
        }
        // GET: admin/BlogArticle
        public ActionResult Index()
        {
            var BlogArticles = BlogArticleServive.QueryWhere(a => true).OrderByDescending(a => a.bCreateTime);
            return View(BlogArticles);
        }

        public ActionResult Add()
        {
            return View();
        }

        //新增博文
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(BlogArticle blogArticle)
        {
            blogArticle.bCreateTime = DateTime.Now;
            blogArticle.bsubmitter = "admin";
            blogArticle.bUpdateTime = DateTime.Now;
            blogArticle.bRemark = string.Empty;
            BlogArticleServive.Add(blogArticle);
            BlogArticleServive.SaverChanges();
            return Content("ok:添加成功！");
        }

        //图片上传
        public ActionResult upload()
        {
            //文件保存目录路径
            String savePath = "/upload/";

            //定义允许上传的文件扩展名
            Hashtable extTable = new Hashtable();
            extTable.Add("image", "gif,jpg,jpeg,png,bmp");
            extTable.Add("flash", "swf,flv");
            extTable.Add("media", "swf,flv,mp3,wav,wma,wmv,mid,avi,mpg,asf,rm,rmvb");
            extTable.Add("file", "doc,docx,xls,xlsx,ppt,htm,html,txt,zip,rar,gz,bz2");

            //最大文件大小
            int maxSize = 1000000;

            HttpPostedFileBase imgFile = Request.Files["imgFile"];
            if (imgFile == null)
            {
                return Content("error|请选择文件。");
            }

            String dirPath = Server.MapPath(savePath);
            if (!Directory.Exists(dirPath))
            {
                return Content("error|上传目录不存在。");
            }

            String dirName = Request.QueryString["dir"];
            if (String.IsNullOrEmpty(dirName))
            {
                dirName = "image";
            }
            if (!extTable.ContainsKey(dirName))
            {
                return Content("error|目录名不正确。");
            }

            String fileName = imgFile.FileName;
            String fileExt = Path.GetExtension(fileName).ToLower();

            if (imgFile.InputStream == null || imgFile.InputStream.Length > maxSize)
            {
                return Content("error|上传文件大小超过限制。");
            }

            if (String.IsNullOrEmpty(fileExt) || Array.IndexOf(((String)extTable[dirName]).Split(','), fileExt.Substring(1).ToLower()) == -1)
            {
                return Content("error|上传文件扩展名是不允许的扩展名。\n只允许" + ((String)extTable[dirName]) + "格式。");
            }

            //创建文件夹
            dirPath += dirName + "/";
            if (!Directory.Exists(dirPath))
            {
                Directory.CreateDirectory(dirPath);
            }
            String ymd = DateTime.Now.ToString("yyyyMMdd", DateTimeFormatInfo.InvariantInfo);
            dirPath += ymd + "/";
            if (!Directory.Exists(dirPath))
            {
                Directory.CreateDirectory(dirPath);
            }

            String newFileName = DateTime.Now.ToString("yyyyMMddHHmmss_ffff", DateTimeFormatInfo.InvariantInfo) + fileExt;
            String filePath = dirPath + newFileName;

            imgFile.SaveAs(filePath);

            String fileUrl = savePath + "image/" + ymd + "/" + newFileName;
            return Content(fileUrl);
        }
    }
}

Wchl.WMBlog.WebUI/Areas/admin/Views/BlogArticle/Add.cshtml
@{
    ViewBag.Title = "添加博客";
}

<link href="~/Content/CSS/animate.css" rel="stylesheet" />
<link href="~/Content/lib/wangEditor/dist/css/wangEditor.css" rel="stylesheet" />
<link href="~/Content/CSS/blogArticleStyle.css" rel="stylesheet" />
<script src="~/Content/lib/wangEditor/dist/js/wangEditor.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script type="text/javascript">
    $(function () {
        // 获取元素
        var textarea = document.getElementById('bcontent');
        // 生成编辑器
        var editor = new wangEditor(textarea);
        // 自定义菜单
        editor.config.menus = [
        'source',
        '|',
        'bold',
        'underline',
        'italic',
        'eraser',
        'forecolor',
        'bgcolor',
        '|',
        'quote',
        'fontfamily',
        'fontsize',
        'head',
        'unorderlist',
        'orderlist',
        'alignleft',
        'aligncenter',
        'alignright',
        '|',
        'link',
        'unlink',
        'emotion',
        '|',
        'img',
        'insertcode',
        '|',
        'undo',
        'redo',
        'fullscreen'
        ];
        // 上传图片（举例）
        editor.config.uploadImgUrl = '/admin/BlogArticle/upload';
        editor.config.uploadImgFileName = 'imgFile'
        editor.create();
    });
    //添加博文之后
    function afterAddBlog(data) {
        var serverData = data.split(':');
        if (serverData[0] == "ok")
        {
            alert(serverData[1]);
            window.location.reload();
        }
    };
</script>
<div class="blogcontent">
    <!-- head star -->
    <div class="tnav row border-bottom white-bg page-heading">
        <div class="col-sm-4">
            <h2 class="fl">博客后台</h2>
            <ol class="breadcrumb fl">
                <li><a href="/admin/Home">博客管理</a></li>
                <li><strong>发布博客</strong></li>
            </ol>
        </div>
    </div>
    <!-- head end -->
    <!-- form star -->
    <div class="">
        <div class="wrapper wrapper-content animated fadeInUp" style="height:600px;padding-bottom:30px;overflow:auto">
            @using (Ajax.BeginForm("Add", "BlogArticle", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterAddBlog" }, new { @class = "form-horizontal" }))
            {
                <div class="form-group">
                    <label class="col-md-1 control-label">标题&nbsp;:</label>
                    <div class="col-md-11">
                        <input type='text' name='btitle' id='title' value='' class='form-control' placeholder='' />
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-1 control-label">类别&nbsp;:</label>
                    <div class='col-md-2'>
                        <select name='bcategory' id='original' class='form-control'>
                            <option value='技术博文' selected='selected'>技术博文</option>
                            <option value='随笔日志'>随笔日志</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-1 control-label">内容&nbsp;:</label>
                    <div class='col-md-11'>
                        <textarea id="bcontent" rows="18" name="bcontent" class='form-control'>
                            <p>请输入内容...</p>
                        </textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-1 col-md-10">
                        <input type='submit' id='submit' class='btn btn-info' value='保存' data-loading='稍候...' />
                    </div>
                </div>

            }
        </div>
    </div>
    <!-- form end -->
</div>

Wchl.WMBlog.WebUI/Areas/admin/Views/BlogArticle/Index.cshtml
@model IEnumerable<Wchl.WMBlog.Model.Models.BlogArticle>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>