Wchl.WMBlog.WebUI/Areas/admin/Controllers/AdvertisementController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wchl.WMBlog.IServices;
using Wchl.WMBlog.Model.Models;
using Wchl.WMBlog.Model.VeiwModels;
using Wchl.WMBlog.WebCore;
using Webdiyer.WebControls.Mvc;

namespace Wchl.WMBlog.WebUI.Areas.admin.Controllers
{
    public class AdvertisementController : BaseController
    {
        IAdvertisementServices AdvertisementServices;
        public AdvertisementController(IAdvertisementServices AdvertisementServices)
        {
            this.AdvertisementServices = AdvertisementServices;
        }

        // GET: admin/Advertisement
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 获取广告信息
        /// </summary>
        /// <returns></returns>
        public ActionResult getData()
        {
            int pageIndex = Request["start"] != null ? int.Parse(Request["start"]) : 1;
            int pageSize = Request["length"] != null ? int.Parse(Request["length"]) : 5;
            int draw = Request["draw"] != null ? int.Parse(Request["draw"]) : 1;
            int totalCount;
            int count = 0;
            var adInfoList = AdvertisementServices.QueryByBeginPage(pageIndex, pageSize, out totalCount, r =>true , r => r.Createdate, false);
            var temp = from u in adInfoList
                       select new { count= count+=1, ID = u.Id, Title = u.Title, ImgUrl = u.ImgUrl, Createdate = u.Createdate,url=u.Url, Remark = u.Remark };
            return Json(new {
                data = temp.ToList(),
                draw = draw,
                recordsTotal = totalCount,
                recordsFiltered = totalCount
            },JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 删除广告
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult del(int id)
        {
            Advertisement model = new Advertisement() {Id=id };
            AdvertisementServices.Delete(model, false);
            AdvertisementServices.SaverChanges();
            return Json(new { status = "0" },JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 添加广告信息
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Add(AdvertisementViewModels model)
        {
            model.Createdate = DateTime.Now;
            //AutoMapper自动映射
            Mapper.Initialize(cfg => cfg.CreateMap<AdvertisementViewModels, Advertisement>());
            Advertisement models = Mapper.Map<AdvertisementViewModels, Advertisement>(model);
            AdvertisementServices.Add(models);
            AdvertisementServices.SaverChanges();
            return Json(new { status="0" },JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 百度上传图片
        /// </summary>
        /// <param name="id">百度插件自定义对图片的命名id</param>
        /// <param name="name">图片名称</param>
        /// <param name="type">图片类型</param>
        /// <param name="lastModifiedDate">图片本身的修改时间</param>
        /// <param name="size">图片大小</param>
        /// <param name="file">文件流</param>
        /// <returns></returns>
        public ActionResult UpLoadProcess(string id, string name, string type, string lastModifiedDate, int size, HttpPostedFileBase file)
        {
            string filePathName = string.Empty;

            string localPath = Server.MapPath("/upload/");
            if (Request.Files.Count == 0)
            {
                return Json(new { jsonrpc = 2.0, error = new { code = 102, message = "保存失败" }, id = "id" });
            }

            string ex = Path.GetExtension(file.FileName);
            filePathName = Guid.NewGuid().ToString("N") + ex;

            string datedir = DateTime.Now.ToString("yyyyMMdd");
            if (!Directory.Exists(localPath + datedir))
            {
                Directory.CreateDirectory(localPath + datedir);
            }
            string path = localPath + datedir;
            try
            {
                file.SaveAs(Path.Combine(path, filePathName));
            }
            catch (Exception)
            {
                return Json(new { jsonrpc = 2.0, error = new { code = 103, message = "保存失败" }, id = "id" });
            }
            return Json(new
            {
                jsonrpc = "2.0",
                id = id,
                filePath =  "/Upload/"+datedir + "/" + filePathName
            });

        }
    }
}

Wchl.WMBlog.WebUI/Areas/admin/Views/Shared/_Layout.cshtml
@using Wchl.WMBlog.WebCore
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 博客系统后台管理</title>
    <link href="~/Content/CSS/zui.css" rel="stylesheet" />
    <link href="~/Content/CSS/zui-theme.css" rel="stylesheet" />
    <link href="//cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/lib/metisMenu/metisMenu.css" rel="stylesheet" />
    <link href="~/Content/CSS/index.css" rel="stylesheet" />
    @RenderSection("stylesheet", required: false)
    <script src="~/Content/JS/jquery-1.12.4.min.js"></script>
    <script src="~/Content/JS/zui.js"></script>
    <script src="~/Content/lib/metisMenu/metisMenu.js"></script>
    <script src="~/Content/JS/index.js"></script>

    <!--[if lt IE 9]>
    <script src="http://libs.useso.com/js/html5shiv/3.7/html5shiv.min.js"></script>
    <script src="http://libs.useso.com/js/respond.js/1.4.2/respond.min.js"></script>
    <script src="lib/ieonly/excanvas.js"></script>
    <![endif]-->

</head>
<body>
    <!--header-->
    <header>
        <div class="navbar navbar-inverse " role="navigation">
            <div class="navbar-header">
                <!--移动设备上的导航切换按钮-->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-example">
                    <span class="sr-only">切换导航</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--品牌名称或logo-->
                <a class="navbar-brand">系统后台</a>
            </div>
            <div class="collapse navbar-collapse navbar-collapse-example">
                <ul class="nav navbar-nav navbar-right">
                    <li><a><i class="icon icon-user"></i>&nbsp;&nbsp;您好，@ViewBag.UserName</a></li>
                    <li><a><i class="icon icon-exchange"></i>&nbsp;&nbsp;隐藏菜单</a></li>
                    <li><a href="/admin/Home"><i class="icon icon-home"></i>&nbsp;&nbsp;首页</a></li>
                    <li><a><i class="icon icon-question-sign"></i>&nbsp;&nbsp;帮助</a></li>
                    <li><a href="/admin/Login/Logout"><i class="icon icon-off"></i>&nbsp;&nbsp;退出</a></li>
                </ul>
            </div>
        </div>
    </header>
    <!--header end-->
    <!--content-->
    <div class="clearfix">
        @Html.Partial("_sidebar")
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 rightmain">
            <div class="col-sm-12  col-md-12  rightcontent">
                @RenderBody()
            </div>
        </div>
    </div>
    <!--content end-->
    <!--footer-->
    <footer class="col-md-12 footer footerstyle">
        <p>&copy; @DateTime.Now.Year - 我的博客系统</p>
    </footer>
    <!--footer end-->

    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Wchl.WMBlog.WebUI/Areas/admin/Views/Shared/_sidebar.cshtml
@{
    string url = Request.Url.ToString().ToLower();
}
@if (url.Contains("home"))
{
    <aside class="col-sm-3 col-md-2 sidebar">
        <nav class="sidebar-nav">
            <ul class="metismenu" id="menu">
                <li class="active">
                    <a href="#" aria-expanded="true">
                        <i class="icon icon-github"></i>
                        系统统计<i class="fa arrow fa-fw"></i>
                    </a>
                    <ul aria-expanded="true">
                        <li>
                            <a href="/admin/statistics/visitor">
                                <i class="icon icon-list"></i>
                                访问统计
                            </a>
                        </li>
                        <li>
                            <a href="/admin/statistics/usesr">
                                <i class="icon icon-github"></i>
                                用户统计
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">博客管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="/admin/BlogArticle/Index">博客列表</a></li>
                        <li><a href="/admin/BlogArticle/Add">发布博客</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">广告管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="@Url.Action("index", "Advertisement")">轮播图管理</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">用户管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="#">修改信息</a></li>
                        <li><a href="#">修改密码</a></li>
                        <li>
                            <a href="#" aria-expanded="false">用户信息管理<span class="fa plus-times"></span></a>
                            <ul aria-expanded="false">
                                <li><a href="#">修改信息</a></li>
                                <li><a href="#">修改密码</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">权限管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="#">用户授权</a></li>
                        <li><a href="#">用户组管理</a></li>
                        <li><a href="#">用户组授权</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">日志管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="#">用户日志</a></li>
                        <li><a href="#">系统日志</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </aside>
}
else if (url.Contains("blogarticle"))
{
    <aside class="col-sm-3 col-md-2 sidebar">
        <nav class="sidebar-nav">
            <ul class="metismenu" id="menu">
                <li>
                    <a href="#" aria-expanded="true">
                        <i class="icon icon-github"></i>
                        系统统计<i class="fa arrow fa-fw"></i>
                    </a>
                    <ul aria-expanded="true">
                        <li>
                            <a href="/admin/statistics/visitor">
                                <i class="icon icon-list"></i>
                                访问统计
                            </a>
                        </li>
                        <li>
                            <a href="/admin/statistics/usesr">
                                <i class="icon icon-github"></i>
                                用户统计
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="active">
                    <a href="#" aria-expanded="false">博客管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="/admin/BlogArticle/Index">博客列表</a></li>
                        <li><a href="/admin/BlogArticle/Add">发布博客</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">广告管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="@Url.Action("index", "Advertisement")">轮播图管理</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">用户管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="#">修改信息</a></li>
                        <li><a href="#">修改密码</a></li>
                        <li>
                            <a href="#" aria-expanded="false">用户信息管理<span class="fa plus-times"></span></a>
                            <ul aria-expanded="false">
                                <li><a href="#">修改信息</a></li>
                                <li><a href="#">修改密码</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">权限管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="#">用户授权</a></li>
                        <li><a href="#">用户组管理</a></li>
                        <li><a href="#">用户组授权</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">日志管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="#">用户日志</a></li>
                        <li><a href="#">系统日志</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </aside>
}
else if (url.Contains("advertisement"))
{
    <aside class="col-sm-3 col-md-2 sidebar">
        <nav class="sidebar-nav">
            <ul class="metismenu" id="menu">
                <li>
                    <a href="#" aria-expanded="true">
                        <i class="icon icon-github"></i>
                        系统统计<i class="fa arrow fa-fw"></i>
                    </a>
                    <ul aria-expanded="true">
                        <li>
                            <a href="/admin/statistics/visitor">
                                <i class="icon icon-list"></i>
                                访问统计
                            </a>
                        </li>
                        <li>
                            <a href="/admin/statistics/usesr">
                                <i class="icon icon-github"></i>
                                用户统计
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">博客管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="/admin/BlogArticle/Index">博客列表</a></li>
                        <li><a href="/admin/BlogArticle/Add">发布博客</a></li>
                    </ul>
                </li>
                <li class="active">
                    <a href="#" aria-expanded="false">广告管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="@Url.Action("index", "Advertisement")">轮播图管理</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">用户管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="#">修改信息</a></li>
                        <li><a href="#">修改密码</a></li>
                        <li>
                            <a href="#" aria-expanded="false">用户信息管理<span class="fa plus-times"></span></a>
                            <ul aria-expanded="false">
                                <li><a href="#">修改信息</a></li>
                                <li><a href="#">修改密码</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">权限管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="#">用户授权</a></li>
                        <li><a href="#">用户组管理</a></li>
                        <li><a href="#">用户组授权</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" aria-expanded="false">日志管理<i class="fa arrow fa-fw"></i></a>
                    <ul aria-expanded="false">
                        <li><a href="#">用户日志</a></li>
                        <li><a href="#">系统日志</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </aside>
}